### ISSUE TITLE
Rename the extension

### ISSUE THREAD

**Issue by jtpio** [hbcarlos/voila-editor#13]
At some point we will want to rename the extension so it is more descriptive.

Maybe something like `@jupyter-voila/jupyterlab-gridstack` or `@jupyter-voila/jupyterlab-gridstack-editor`, since there is already `@jupyter-voila/jupyterlab-preview`?

Also we'll probably move it to the https://github.com/voila-dashboards/voila-gridstack once it is ready to be published.

**Comment by hbcarlos** [comment]
It's fine for me. But I was thinking of implementing one JupyterLab extension to edit the notebook info for all the templates, gridstack, reveal, ...

What are your thoughts?
