### ISSUE TITLE
Add test structure.

### ISSUE THREAD

**Issue by hbcarlos** [hbcarlos/voila-editor#58]
We can use https://github.com/jupyterlab/debugger/tree/master/test as an example.

**Comment by jtpio** [comment]
Then there could be a new step on CI to run the tests (even if there are none in the beginning).

Similar to:

https://github.com/hbcarlos/voila-editor/blob/52f8ed6fa12f3eba752bbc79b24543cd928c1637/.github/workflows/build.yml#L35-L39

But running `jlpm run test` instead.

**Comment by jtpio** [comment]
Fixed by #61
