### ISSUE TITLE
Editing Markdown cells

### ISSUE THREAD

**Issue by jtpio** [hbcarlos/voila-editor#67]
It would be nice if editing a markdown cell would also update the view in the gridstack editor:

![edit-markdown](https://user-images.githubusercontent.com/591645/100765487-d47f8e00-33f7-11eb-9ab8-2902bc47a7d1.gif)

Also, it looks like changing the cell type adds new items to the gridstack view, while users might expect it to stay the same:

![edit-cell-type](https://user-images.githubusercontent.com/591645/100765497-d6e1e800-33f7-11eb-85b9-82f3c7596b21.gif)

**Comment by hbcarlos** [comment]
Thanks for finding this out Jeremy. I'm gonna work on this today.
